name: 'Preview Request Action'
description: 'Action template for preview request'
author: 'zezaeoh <zezaeoh@github.com>'
inputs:
  application:
    required: true
    description: 'application id (name)'
  branch:
    required: true
    description: 'branch name'
  pr-title:
    required: true
    description: 'title of pull request'
  pr-url:
    required: true
    description: 'url of pull request'
  pr-assignee:
    required: false
    description: 'assignee of pull request'
  image-tag:
    required: true
    description: 'docker image tag to deploy'
  profile:
    required: true
    description: 'base profile'
  base-domain:
    required: true
    description: 'base domain name'
  destination:
    required: true
    description: 'destination cluster name to deploy'
  override-values:
    required: false
    description: 'values to override, json format'
outputs:
  endpoint:
    description: 'endpoint url of preview service'
  context:
    description: 'context of preview request'
runs:
  using: 'node12'
  main: 'dist/index.js'
